// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn3TgKpLpyGnHtQ8nLyDGXGQSU4ChfiYo',
    appId: '1:836469921237:web:43aa0bd620abb78db9995c',
    messagingSenderId: '836469921237',
    projectId: 'firedection-a6dbe',
    authDomain: 'firedection-a6dbe.firebaseapp.com',
    databaseURL: 'https://firedection-a6dbe-default-rtdb.firebaseio.com',
    storageBucket: 'firedection-a6dbe.firebasestorage.app',
    measurementId: 'G-NNVR9KT4YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuxSD01-xd985n5IG7Xo1r0GpnN5dGpe8',
    appId: '1:836469921237:android:47d0ef100b7795dfb9995c',
    messagingSenderId: '836469921237',
    projectId: 'firedection-a6dbe',
    databaseURL: 'https://firedection-a6dbe-default-rtdb.firebaseio.com',
    storageBucket: 'firedection-a6dbe.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn3TgKpLpyGnHtQ8nLyDGXGQSU4ChfiYo',
    appId: '1:836469921237:web:b2bbe85b7bdf1416b9995c',
    messagingSenderId: '836469921237',
    projectId: 'firedection-a6dbe',
    authDomain: 'firedection-a6dbe.firebaseapp.com',
    databaseURL: 'https://firedection-a6dbe-default-rtdb.firebaseio.com',
    storageBucket: 'firedection-a6dbe.firebasestorage.app',
    measurementId: 'G-6DZ4DB2NES',
  );
}